### PR TITLE
Feature/fix test that breaks on master

### LINKED ISSUE #46: "Basic golden test for empty container Animation test with CustomPump Golden" is failing for me since day 1
The " Basic golden test for empty container Animation test with CustomPump Golden" test fails with a diff of 3.06% for me since the first commit.

Could anyone confirm that?

### PR DESCRIPTION
**Pull request by coreysprague**
fixes #46 

updated a test not coupled to CircularProgressIndicator (as that widget has different UI on flutter master).

Unrelated change -  added a deprecated flag to a couple of parameters

### CODE REVIEW

File: packages/golden_toolkit/test/screen_matches_golden_test.dart [hunk 1]
```diff
@@ -3,23 +3,36 @@ import 'package:flutter_test/flutter_test.dart';
 import 'package:golden_toolkit/src/testing_tools.dart';
 
 void main() {
-  testGoldens('Animation test with CustomPump', (tester) async {
+  testGoldens('Custom Pump should be evaluated if supplied', (tester) async {
```
Comment (coreysprague) [inline packages/golden_toolkit/test/screen_matches_golden_test.dart:6]: this test started failing on Flutter Master because something changed with CircularProgressIndicator.

The circular progress indicator was an implementation detail of the test that distracted from the actual test case. Reworked the test to better demonstrate how customPump (btw, I HATE that name...) can be used for fine grained control of pumping... this should be less brittle. Verified it passes successfully on both stable & master
